# Generated by Django 4.1.5 on 2023-04-18 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Status_Obj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_out", models.DateTimeField(auto_created=True)),
                ("title", models.CharField(max_length=150)),
                ("local", models.CharField(max_length=255)),
                ("date_arrived", models.DateTimeField(auto_now_add=True)),
                (
                    "last_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Data_Objects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("brand", models.CharField(max_length=255, verbose_name="Marca")),
                (
                    "manufacturer",
                    models.CharField(max_length=255, verbose_name="Fabricante"),
                ),
                ("serial_num", models.SlugField(verbose_name="Numero de Série")),
                ("type_obj", models.CharField(max_length=255, verbose_name="Tipo")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dataObjects.status_obj",
                    ),
                ),
            ],
            options={"verbose_name": "Objeto", "verbose_name_plural": "Objetos",},
        ),
    ]
