# Generated by Django 4.1.5 on 2023-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status_obj",
            name="local",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
