# Generated by Django 4.1.5 on 2023-04-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0002_alter_status_obj_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data_objects",
            name="status",
            field=models.ForeignKey(
                default="O",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dataObjects.status_obj",
            ),
        ),
        migrations.AlterField(
            model_name="status_obj",
            name="date_arrived",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="status_obj",
            name="date_out",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
