# Generated by Django 4.1.5 on 2023-04-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0003_alter_data_objects_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="data_objects",
            name="quantity",
            field=models.IntegerField(default=1, null=True, verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="data_objects",
            name="status",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dataObjects.status_obj",
            ),
        ),
    ]
