# Generated by Django 4.1.5 on 2023-04-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0004_data_objects_quantity_alter_data_objects_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="status_obj",
            name="qty_used",
            field=models.IntegerField(null=True),
        ),
    ]
