# Generated by Django 4.1.5 on 2023-04-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0005_status_obj_qty_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status_obj",
            name="qty_used",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
