# Generated by Django 4.1.5 on 2023-04-27 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dataObjects", "0009_alter_data_objects_serial_num"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status_obj",
            options={
                "verbose_name": "Status dos Materiais",
                "verbose_name_plural": "Status dos Materiais",
            },
        ),
        migrations.AlterField(
            model_name="data_objects",
            name="serial_num",
            field=models.SlugField(null=True, verbose_name="Numero de Série"),
        ),
        migrations.AlterField(
            model_name="status_obj",
            name="date_arrived",
            field=models.DateTimeField(auto_now=True, verbose_name="Data de Retorno"),
        ),
        migrations.AlterField(
            model_name="status_obj",
            name="date_out",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data de Saida"),
        ),
        migrations.AlterField(
            model_name="status_obj",
            name="last_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsavel",
            ),
        ),
        migrations.AlterField(
            model_name="status_obj",
            name="local",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Local de utilização",
            ),
        ),
        migrations.AlterField(
            model_name="status_obj",
            name="obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dataObjects.data_objects",
                verbose_name="Equipamento",
            ),
        ),
        migrations.AlterField(
            model_name="status_obj",
            name="qty_used",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade usada"
            ),
        ),
        migrations.AlterField(
            model_name="status_obj",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Titulo"),
        ),
    ]
