# Generated by Django 4.1.5 on 2023-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0010_alter_status_obj_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="status_obj",
            name="id_os",
            field=models.IntegerField(null=True, verbose_name="ID OS"),
        ),
    ]
