# Generated by Django 4.1.5 on 2023-04-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0013_alter_status_obj_id_os"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requests_To_Out",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Titulo")),
                (
                    "local",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Local de utilização",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="status_obj", name="local",),
        migrations.RemoveField(model_name="status_obj", name="title",),
        migrations.AlterField(
            model_name="status_obj",
            name="id_os",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dataObjects.requests_to_out",
            ),
        ),
    ]
