# Generated by Django 4.1.5 on 2023-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0014_requests_to_out_remove_status_obj_local_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requests_to_out",
            options={
                "verbose_name": "Solicitação de Saida",
                "verbose_name_plural": "Solicitações de Saida",
            },
        ),
        migrations.AlterModelOptions(
            name="status_obj",
            options={
                "verbose_name": "Status do Material",
                "verbose_name_plural": "Status dos Materiais",
            },
        ),
        migrations.AddField(
            model_name="requests_to_out",
            name="doc_out",
            field=models.FilePathField(
                default="/media/", verbose_name="Caminho do arquivo"
            ),
            preserve_default=False,
        ),
    ]
