# Generated by Django 4.1.5 on 2023-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0015_alter_requests_to_out_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requests_to_out",
            name="doc_out",
            field=models.CharField(max_length=255, verbose_name="Caminho do arquivo"),
        ),
    ]
