# Generated by Django 4.1.5 on 2023-05-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataObjects", "0016_alter_requests_to_out_doc_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="requests_to_out",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
    ]
